### ISSUE TITLE
How do I use this to make a test chain?

### ISSUE THREAD

**Issue by plato-cambrian** [ethereum/genesis_block_generator#16]
The [cli docs](https://www.ethereum.org/cli) say I should experiment on my own private test chain so I can easily mine.

They link to [this blog post](https://blog.ethereum.org/2015/07/27/final-steps/) which only has instructions for generating the real genesis block.

I asked on IRC and azariah said I should use this but change the block difficulty. 
Do I really need to fetch real network transactions to construct a test chain genesis block?

**Comment by tgerring** [comment]
You can use any genesis block you want the clients... Find an example online and change the allocation addresses to only include your private net address with lots of wei and low difficulty.

**Comment by plato-cambrian** [comment]
ok thanks, is this repo the wrong place for my issue? i.e. should the python script NOT make test genesis blocks?

**Comment by obscuren** [comment]
[this](http://jev.io/example_genesis.json) is a genesis file that you can use. If you'd like to give yourself a lot of Ether can you add your address in between the `alloc` part:

``` json
"alloc": {
    "0xmyaddress": {
        "balance": "10000000000"
    }
}
```

**Comment by plato-cambrian** [comment]
Thanks guys!

**Comment by plato-cambrian** [comment]
in case that link dies:

```
No allocation
{
    "nonce": "0xdeadbeefdeadbeef",
    "timestamp": "0x0", 
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000", 
    "extraData": "0x686f727365", 
    "gasLimit": "0x8000000", 
    "difficulty": "0x400", 
    "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000", 
    "coinbase": "0x3333333333333333333333333333333333333333",
    "alloc": {
   }
}

Allocating to one address:
"alloc": {
    "0xmyaddress": {
        "balance": "10000000000"
    }
}
```

One last question, that balance is in "Wei's", right? so that number would actually be some miniscule fraction of one "ether" and probably not enough to deploy a contract?

**Comment by obscuren** [comment]
That's indeed wei. Just supply an amount less than `2**256` :-)
